from DoubleCycleLinkedList import DoubleCycleLinkedList

d = DoubleCycleLinkedList()
d.insert_head(10)
print(d)
d.insert_head(20)
d.insert_head(30)
print(d)
d.insert_tail(40)
d.insert_tail(50)
print(d)
print(d.delete_head())
print(d.delete_head())
print(d.list_size())
print(d)
print(d.delete_tail())
print(d)
print(d.delete_tail())
print(d)
print(d.delete_tail())
print(d)
print(d.delete_tail())
print(d)
d.insert_head(20)
d.insert_head(30)
print(d)
print(d.find_head())
print(d.find_tail())
print(d.delete_tail())
print(d.delete_tail())
print(d.find_head())
print(d.find_tail())