from SingleLinkedList import SingleLinkedList

l = SingleLinkedList()
l.insert_head(10)
print(l)
l.insert_head(20)
l.insert_head(30)
print(l)
l.insert_tail(40)
print(l)
print(l.list_size())
l.insert_tail(50)
print(l)
print(l.find_head())
print(l.find_tail())
print(l)
print(l.delete_head())
print(l)
print(l.list_size())
print(l.delete_tail())
print(l)
print(l.list_size())
print(l.delete_tail())
print(l.delete_tail())
print(l.delete_tail())
print(l.delete_tail())
print(l.list_size())